sudo: false

language: node_js

node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm config set spin false
  - npm install -g npm@latest

  - npm install

script:
  - npm run build:prod
  - npm run build:aot

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH
